### ISSUE TITLE
Asset information display issue

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-app#13]
One needs to click twice on (the first) asset one wants to display information for.

Clicking on an asset should display its information modal right away.

**Comment by chalabi2** [comment]
this was fixed in #87

**Comment by fmorency** [comment]
@chalabi2 I still see that behavior on the latest deployment.

**Comment by fmorency** [comment]
Fixed by #116
